components:
  headers:
    - Cache-Control:
        description: |
          The RFC 7234 Cache-Control header field is providing directives to
          control how proxies and clients are allowed to cache responses results
          for performance. Clients and proxies are free to not support caching of
          results, however if they do, they must obey all directives mentioned in
          [RFC-7234 Section 5.2.2](https://tools.ietf.org/html/rfc7234) to the
          word.

          In case of caching, the directive provides the scope of the cache
          entry, i.e. only for the original user (private) or shared between all
          users (public), the lifetime of the cache entry in seconds (max-age),
          and the strategy how to handle a stale cache entry (must-revalidate).
          Please note, that the lifetime and validation directives for shared
          caches are different (s-maxage, proxy-revalidate).

        type: string
        required: false
        example: 'private, must-revalidate, max-age=300'

    - Vary:
        description: |
          The RFC 7231 Vary header field in a response defines which parts of
          a request message, aside the target URL and HTTP method, might have
          influenced the response. A client or proxy cache must respect this
          information, to ensure that it delivers the correct cache entry (see
          [RFC-7231 Section
          7.1.4](https://tools.ietf.org/html/rfc7231#section-7.1.4)).

        type: string
        required: false
        example: 'accept-encoding, accept-language'
