securitySchemes:
  oauth2:
    type: oauth2
    flows:
      clientCredentials:
        tokenUrl: https://identity.zalando.com/oauth2/token
        scopes:
          fulfillment-order-service.read: Access right needed to read from the fulfillment order service.
          fulfillment-order-service.write: Access right needed to write to the fulfillment order service.
